
const Test = require('./controllers/test');
const config = require('./config');
const jwt = require('jwt-simple');


const passportService = require('./services/passport');//necessary for passport to work
const passport = require('passport');


function tokenForUser(user){
  const timestamp = new Date().getTime();

  return jwt.encode({sub:user.id,iat:timestamp},config.secret || process.env.SECRET);//user.id is a proxy for user._id which is generated by mongo
}                                                             //secret is combined with sub & iat to create token


module.exports = function(app){

app.post('/test',Test);


}
